var Say, extractValues, path, request;

extractValues = require('extract-values');

path = require('path');

request = require('request');

Say = (function() {
  function Say(phrase) {
    var getLink;
    this.phrase = phrase;
    this.link = '';
    this.formData = {
      MyLanguages: 'sonid9',
      MySelectedVoice: 'Graham',
      MyTextForTTS: "" + this.phrase,
      SendToVaaS: ''
    };
    this.options = {
      headers: {
        ' content-type': 'Content-type: application/x-www-form-urlencoded\r\n'
      }
    };
    (getLink = function(options, formData, bodyLink) {
      this.options = options;
      this.formData = formData;
      this.bodyLink = bodyLink;
      return request.post({
        url: 'http://www.acapela-group.com/demo-tts/DemoHTML5Form_V2.php',
        headers: this.options.headers,
        form: this.formData
      }, function(error, response, body) {
        body = extractValues(JSON.stringify(response), "var myPhpVar = '{link}\';");
        this.bodyLink = body.link;
        this.link = this.bodyLink;
        console.log({
          link: this.link
        });
        return {
          link: this.link
        };
      });
    })(this.options, this.formData, this.bodyLink);
  }

  return Say;

})();

module.exports = Say;

Say('hello');

// ---
// generated by coffee-script 1.9.2
